#!groovy
def getData(){  
    return "testing"
}
pipeline {
    agent any
     parameters {    	
        choice(name: 'ENVIRONMENT', choices: 'DEVELOPMENT\nTEST\nSTAGING_EDC\nSTAGING_WTC\nPRODUCTION_EDC\nPRODUCTION_WTC', description: 'Which Environment?')
      }
	   environment {

        CREDENTIAL_ID = getData()
        API_URL = "https://www.google.com"
		ORG = "456"
        SPACE = "DEVELOPMENT"
		
		}
	  
     stages {
        stage('Initialize') {
            steps {
		    
		    script{
		     if (env.CREDENTIAL_ID) {
                        withCredentials([usernamePassword(credentialsId: env.PAAS_PRODUCTION_WTC_CREDENTIAL_ID, passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                                env.PAAS_PRODUCTION_WTC_USERNAME = USER
                                env.PAAS_PRODUCTION_WTC_PASSWORD = PASS
                        }
                    }
		    }
			echo 'hellooooo'
		    echo ${CREDENTIAL_ID}
          //      echo 'setting...'   
         //        bat 'set'
            }
        }
     
    }
    post { 
        always { 
           
             echo 'CDUS build is Completed!'
        }
    }
}
