pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'              
            }
        }
        
        stage ('Clone') {
             steps {
        git url: 'https://github.com/karthickwiz/jenkins.git'
             }
    }
         stage ('Clone') {
             steps {
        bat 'gradlew.bat clean build'
             }
    }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}
