pipeline {
    agent any
     stages {
        stage('Initialize') {
            steps {
                echo 'setting...'   
                 bat 'set'
            }
        }
       stage('build') {
          steps {                                
             bat 'echo building....'
             bat 'gradle build'
               bat 'echo builded....'    
            
          }
       }
        stage('try') {
          steps {
             bat 'echo changing path....'
           //  bat 'cd E:\\git\\repo\\demo'
          //   bat 'gradle build'
               bat 'echo builded....'    
            
          }
       }
stage('Sonarqube analysis') {
    steps {
   echo "sonar report"
 
    }
        }
    }
    post { 
        always { 
            script {
          // requires SonarQube Scanner 2.8+
          scannerHome = tool 'sonar'
        }
  
       
     withSonarQubeEnv('clsd') {
         echo scannerHome
         bat "${scannerHome}/bin/sonar-scanner.bat\
         -Dsonar.projectKey=clsd\
         -Dsonar.projectName=clsd\
         -Dsonar.sources=./demo/src/main/java/com/example/demo\
         -Dsonar.tests=./\
         -Dsonar.test.inclusions=**/*test*/**" 
    }
             echo 'DONE!'
        }
    }
}
