pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'
                bat 'set'
                echo 'done'
            }
        }
    }
    post { 
        always { 
             deleteDir()
            echo 'I will always say Hello again!'
        }
    }
}
